admin:
  - 'code/modules/admin/**'
  - 'whitesands/code/modules/admin/**'

# Any file within the config subfolder
config:
  - 'config/**'

dependencies:
  - '**/package.json'
  - '**/package-lock.json'
  - '**/yarn.lock'

# Any .dmi changes
sprites:
  - '**/*.dmi'

# Changes to a .dmm or anything in the _map subfolder
mapping:
  - '**/*.dmm'
  - '_maps/**'

# Any changes to .ogg files are marked as sound
sound:
  - '**/*.ogg'

# Changes to the SQL subfolder
SQL:
  - 'SQL/**'

# Changes to the tgui subfolder
tgui:
  - 'tgui/**'

# Changes to the .Github subfolder
Github:
  - '.github/**'
